config/routes.rb
Rails.application.routes.draw do
  get 'orders/:item_id/complete', to: 'orders#complete'
  get 'orders/:item_id/cancel', to: 'orders#cancel'
  get 'orders/:item_id', to: 'orders#new', as: 'new_order'
  get 'locations/new', to: 'locations#new', as: 'new_location'
  post 'locations/new', to: 'locations#create'
  post 'buckets/:bucket_id/items/new', to: 'items#create'
  post 'buckets/:bucket_id/items/:item_id/edit', to: 'items#update'
  post 'buckets/:bucket_id/items/:item_id', to: 'tagwords#create'
  get 'buckets/:bucket_id/items/:item_id/:tagword/remove', to: 'tagwords#remove', as: 'tagword_remove'
  resources :locations, only: [:show, :edit, :create, :update]
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'buckets/user', to: 'buckets#user', as: 'user_buckets'

  resources :buckets do 
    get 'destroy', to: 'buckets#destroy', as: 'destroy' 
    post 'items/new', to: 'items#create'
    get 'items/:id/destroy', to: 'items#destroy', as: 'item_destroy'
    resources :items do
      
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user_profile'
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  validates :name, presence: true, length: {minimum: 4}
  validates :description, presence: true, length: {minimum: 10}

  belongs_to :user
  has_many :items, dependent: :destroy

  
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :params_bucket, only: [:show, :edit, :update]
  before_action :authenticate_user!
  before_action :authorize_user, only: [:edit, :destroy]

  require 'geocoder'

  def index
    @location = current_user.location
    @locations = Location.all

    @users = User.all
    @sortedusers = []
    @locations.each do |location|
        unless location === @location
        @sortedusers << [location.distance_to(@location), location]
        end
      end

    @sortedusers = @sortedusers.sort

    if params[:search] != nil
      @items = Item.where('name LIKE ?', ("%#{params[:search]}%" || "%#{params[:search].upcase}%" || "%#{params[:search].downcase}%" || "%#{params[:search].capitalize}%"))
      @allitems = []
      @items.each do |item|
        @allitems << item
      end 
      @buckets = []
      @allitems.each do |item|
        @buckets << item.bucket
      end
      @buckets = @buckets.uniq

      if @buckets == nil 
        flash[:alert] = "Could not find any matching items!"
      end
    else
      @buckets = Bucket.all.order(user_id: :desc)
    end
  end

  def user
    if current_user.buckets.count > 0
      @buckets = current_user.buckets.all
    else
      @buckets = nil
    end
  end

  def show
    @bucket = Bucket.find(params[:id])
    @user = @bucket.user
  end

  def new
    @bucket = Bucket.new
  end

  def create
    @bucket = Bucket.new(bucket_params)
    @bucket.user = current_user
    if @bucket.save
      redirect_to @bucket
    else
      flash[:alert] = "Could not save!"
      render :new
    end
  end

  def edit
  end

  def update 
    if @bucket.update(bucket_params)
      redirect_to @bucket
    else
      flash[:alert] = "Could not update bucket!"
      render :edit
    end
  end

  def destroy 
    Bucket.find(params[:bucket_id]).destroy
    redirect_to buckets_path
  end

  private

  def authorize_user
    if (Bucket.find(params[:id]).user != current_user) && (current_user.has_role?(:admin) == false)
      flash[:alert] = "You are not authorized to view this page!"
      redirect_to root_path
    end
  end

  def params_bucket
    @bucket = Bucket.find(params[:id])
  end

  # Paramater sanitization

  def bucket_params
    params.require(:bucket).permit(:name, :description)
  end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/edit.html.erb
<%= render 'shared/errors', object:@bucket %>
<div class="newbucket">

  <h1>Edit "<%= @bucket.name %>"</h1>

  <%= form_with model: @bucket, local: true do |f| %>

  <p><%= f.text_field :name %></p>
  <p><%= f.text_area :description %></p>
  <p><%= f.submit class: "button is-link" %></p>

  <% end %>

</div>

app/views/buckets/index.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
<% end %>

<% if params[:search] == nil %>
<div class="bucketsinfo">
  <p>Hey look down there, it's you, <%= current_user.username %>!  Though, maybe you should zoom out to find out some products!</p>
</div>
<% end %>



<% if !@allitems %>
<div id="map">
</div>
<% end %>


<div class="search">
  <%= form_tag(buckets_path, method: :get) do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search products', class: "button is-link" %>
  <% end %>
</div>




<div class="allbuckets">
  <h2 class="indextitle">All buckets, sorted by proximity:</h2>
  <% if @allitems %>

    <% @allitems.each do |item| %>
      <div class="bucketcard">
        <div>
        <p>Name: <%= link_to item.name, bucket_item_path(item, item.id, item.bucket.id) %></p>
        <p>User: <%= link_to item.bucket.user.username, user_profile_path(item.bucket.user) %></p>
        </div>
        <div>
        <p>Description: <%= item.description %></p>
        </div>
      </div>
    <% end %>
    
  <% else %>

    <% @sortedusers.each do |user| %>
      <% user[1].user.buckets.each do |bucket| %>
        <div class="bucketcard">

          <div>
            <p>Name: <%= link_to bucket.name, bucket_path(bucket) %></p>
            <p>User: <%= link_to bucket.user.username, user_profile_path(bucket.user) %></p>
            <p><%= user[0].round(2) %> kilometers away</p>
          </div>

          <div>
          <p>Description: <%= bucket.description %></p>
          </div>

        </div>

        <% if bucket.user == current_user %>
          <div class="bucketcard">
            <p><%= link_to "Delete this bucket", bucket_destroy_path(bucket), :data => {:confirm => 'Are you sure?  This will delete any items in the bucket too.'} %></p>
            <p><%= link_to "Edit this bucket", edit_bucket_path(bucket) %></p>
          </div>
        <% end %>

      <% end %>
    <% end %>
  <% end %>
</div>

  <script>

    var users = <%= @users.to_json.html_safe %>
    
    var place = <%= @location.to_json.html_safe %>
    var places = <%= @locations.to_json.html_safe %>;
    var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
    let locations = [];
    var people = [];
    
    function initMap(lat, lng) {
      var myCoords = new google.maps.LatLng(lat, lng);
      var mapOptions = {
        center: myCoords,
        zoom: 16
      }
    
      var map = new google.maps.Map(document.getElementById('map'), mapOptions);
      
      for (var i = 0; i < places.length; i++) {
          locations.push({lat: places[i].latitude, lng: places[i].longitude, id: (places[i].user_id - 1)}),
          // console.log({lat: places[i].latitude, lng: places[i].longitude, id: (places[i].user_id)}),
          people.push({user: users[i], location_id: places[i]})
      }
      console.log(locations)
    
    
      var markers = locations.map(function(location, i) {
        if (location.lat != place.latitude || location.lng != place.longitude) {
          return addMarker(location, map)
        } else {
          return new google.maps.Marker({
          position: location,
        })
      }
    })
        
        var markerCluster = new MarkerClusterer(
          map,
          markers,
          {
            imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m', 
            clusteringOptions: {
              eps: 10,
            }
          }
        )
    
    }
    
    function addMarker(place, map) {
      place.lat += Math.random() * (0.0015 - 0.001) + 0.0001;
      place.lng += Math.random() * (0.0015 - 0.001) + 0.0001;
      var marker = new google.maps.Marker({
        position: { lat: place.lat, lng: place.lng},
        map: map,
        icon: "https://upload.wikimedia.org/wikipedia/commons/c/ca/1x1.png"
      });  
      console.log(place)
      var infowindow = new google.maps.InfoWindow({
        
        content: "<a href='https://mysterious-coast-47299.herokuapp.com/users/" + users[place.id].id + "'><em>" + people[place.id].user.username + "</em></a>"
      });
    
      var circle = new google.maps.Circle({
        map: map,
        clickable: true,
        fillColor: '##3d94ff',
        radius: 75,
      });
    
      circle.bindTo('center', marker, 'position')
      infowindow.bindTo('center', marker, 'position')
    
      map.addListener('click', function() {
        infowindow.close(map)
      });
    
      circle.addListener('click', function() {
        map.setCenter(marker.getPosition());
        infowindow.open(map, marker)
      });
    
      return marker
    }
    
    document.addEventListener("DOMContentLoaded", function(){
        initMap(place.latitude, place.longitude)
    });
    
    </script>
    
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js" >
    </script>

app/views/buckets/new.html.erb
<%= render 'shared/errors', object:@bucket %>

<h1>Create a new bucket!</h1>

<%= form_with model: @bucket, local: true do |f| %>

<div class="form">

  <p><%= f.text_field :name, placeholder: "Enter a bucket name" %></p>
  <p><%= f.text_area :description, placeholder: "Enter a bucket description" %></p>
  <p><%= f.submit %></p>

</div>

<% end %>

app/views/buckets/show.html.erb
<div class="bucket">

<div class="bucket_title">
  <h1><%= @bucket.name %></h1>
  <p>"<%= @bucket.description %>"</p>
  <% if current_user == @bucket.user %>
    <%= link_to "Edit Bucket", edit_bucket_path(@bucket), class: "button is-link" %>
    <%= link_to "Delete Bucket", bucket_destroy_path(@bucket), :data => {:confirm => 'Are you sure?  This will delete any items in the bucket too.'}, class: "button is-link" %>
  <% end %>
</div>


<% if @bucket.items.count > 0 %>
  <div class="user_buckets">
  <% @bucket.items.each do |item| %>
    <% if item.sold == false %>

    <div class="itemcard">
      <div>
        <p><%= link_to item.name, bucket_item_path(@bucket, item.id) %></p>
        <p><%= item.brand %></p>
        <p><%= number_to_currency(item.price) %></p>
        <% if ((item.bucket.user == current_user) || (current_user.has_role?(:admin))) %>
        <p><%= link_to "Delete this item", bucket_item_destroy_path(@bucket.id, item), data: {confirm: 'Are you sure you want to delete this item?'} %></p>
        <p><%= link_to "Edit this item", edit_bucket_item_path(@bucket.id, item) %></p>
        <% end %>
      </div>
      <div>
        <p><%= item.description %></p>
        <p><%= item.returnable %></p>
      </div>
      <% if item.image.attached? %>
      <div class="item_thumbnail">
        <span><%= image_tag item.image %></span>
      </div>
      <% end %>
    </div>
    <% end %>
  <% end%>
  </div>
  <%= link_to "Add an item", new_bucket_item_path(@bucket), class: "button is-link" if current_user == @user %>
  <% else %>
</div>
<div class="noitems">
  <p><%= @bucket.name %> has no items yet!  <%= link_to "Add some now!", new_bucket_item_path(@bucket), class: "button is-link" if current_user == @user %></p>
<% end %>

</div>

app/views/buckets/user.html.erb
<h1>All of your buckets</h1>

<% if @buckets != nil %>

<div class="user_buckets">
 
  <% @buckets.each do |bucket| %>

  <div class="bucket_card">
    <div>
      <p><%= link_to bucket.name, bucket_path(bucket) %></p>
      <p>"<%= bucket.description %>"</p>
    </div>
    <% if (bucket.user == current_user) || (current_user.has_role?(:admin)) %>
    <div class="edit_destroy">
      <p><%= link_to "Delete", bucket_destroy_path(bucket), :data => {:confirm => 'Are you sure?  This will delete any items in the bucket too.'}, class: "button is-link" %></p>
      <p><%= link_to "Edit", edit_bucket_path(bucket), class: "button is-link" %></p>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
<% else %>
  <p>You have no buckets yet!</p>
<% end %>
<p class="new_bucket"><%= link_to "Create a new bucket!", new_bucket_path, class: "button is-link" %></p>