config/routes.rb
Rails.application.routes.draw do
  get 'orders/:item_id/complete', to: 'orders#complete'
  get 'orders/:item_id/cancel', to: 'orders#cancel'
  get 'orders/:item_id', to: 'orders#new', as: 'new_order'
  get 'locations/new', to: 'locations#new', as: 'new_location'
  post 'locations/new', to: 'locations#create'
  post 'buckets/:bucket_id/items/new', to: 'items#create'
  post 'buckets/:bucket_id/items/:item_id/edit', to: 'items#update'
  post 'buckets/:bucket_id/items/:item_id', to: 'tagwords#create'
  get 'buckets/:bucket_id/items/:item_id/:tagword/remove', to: 'tagwords#remove', as: 'tagword_remove'
  resources :locations, only: [:show, :edit, :create, :update]
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'buckets/user', to: 'buckets#user', as: 'user_buckets'

  resources :buckets do 
    get 'destroy', to: 'buckets#destroy', as: 'destroy' 
    post 'items/new', to: 'items#create'
    get 'items/:id/destroy', to: 'items#destroy', as: 'item_destroy'
    resources :items do
      
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  validates :name, presence: true, length: {minimum: 4}
  validates :description, presence: true, length: {minimum: 10}

  belongs_to :user
  has_many :items, dependent: :destroy

  
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id, receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_user)
    self.sender_id == current_user.id ? self.receiver : self.sender
  end

  def unread_message_count(current_user)
    return self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :brand, presence: true, length: {minimum: 2}
  validates :description, presence: true, length: {minimum: 20}
  validates :returnable, presence: true
  validates :price, presence: true
  has_one_attached :image
  has_many :item_tagwords, dependent: :destroy
  has_many :tagwords, through: :item_tagwords
  

  belongs_to :bucket
end

app/models/item_tagword.rb
class ItemTagword < ApplicationRecord
  belongs_to :item
  belongs_to :tagword
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  geocoded_by :full_street_address

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_street_address
    address
  end

  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles



belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/tagword.rb
class Tagword < ApplicationRecord
  has_many :item_tagwords, dependent: :destroy
  has_many :items, through: :item_tagwords
  validates :tag, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :assign_default_role
  has_many :buckets, dependent: :destroy
  validates :username, presence: true
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  has_one :location, dependent: :destroy
  has_many :conversations

  def assign_default_role
    add_role(:user)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :params_item, only: [:show, :edit]
  before_action :authenticate_user!
  before_action :ensure_user, only: :edit
  def index
    @items = Item.all
  end

  def show
    @tagword = Tagword.new
  end

  def new
    @item = Item.new
    @bucket = Bucket.find(params[:bucket_id])
  end

  def create 
    @bucket = Bucket.find(params[:bucket_id])
    @item = @bucket.items.new(item_params)
    @item.image.attach(item_params[:image])
    if @item.save
      redirect_to bucket_path(@bucket)
    else
      flash[:alert] = "Could not save this item!"
      render :new
    end
  end

  def edit
    
  end

  def update 
    @item = Item.find_by(item_params[:item_id])
    if @item.update(item_params)
      redirect_to bucket_item_path(@item.bucket, @item)
    else
      flash[:alert] = "Could not update item!"
      render :edit
    end
  end

  def destroy 
    
    @item = Item.find_by(id: params[:id])
    @bucket = Bucket.find_by(id: params[:bucket_id])
    @item.destroy
    redirect_to bucket_path(@bucket)
    
    
  end 

  private 

  def params_item
    @item = Item.find(params[:id])
  end

  # Paramater sanitization
  def ensure_user
    if (Item.find(params[:id]).bucket.user != current_user) && (current_user.has_role?(:admin) == false)
      flash[:alert] = "You are not authorized to view this page!"
      redirect_to root_path
    end
  end

  def item_params
    params.require(:item).permit(:name, :brand, :description, :returnable, :price, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    

    @user = User.find_by(id: params[:id])
    @sold = []
    @user.buckets.each do |bucket|
      bucket.items.each do |item|
        if item.sold == true
          @sold << item
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tagwords_helper.rb
module TagwordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<%= render 'shared/errors', object:@item %>

<h1>Edit <%= @item.name %></h1>

<%= form_with scope: @item, local: true do |f| %>

<p><%= f.text_field :name%></p>
<p><%= f.text_field :brand %></p>
<p><%= f.text_area :description %></p>
<p><%= f.text_area :returnable %></p>
<p><%= f.number_field :price, step: :any %></p>
<p><%= f.submit %></p>
<% end %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<%= render 'shared/errors', object:@item %>

<h1>Add an item to <%= @bucket.name %></h1>
<div class="new_item">
<%= form_with scope: @item, local: true do |f| %>

<p><%= f.text_field :name, placeholder: "Enter a name" %></p>
<p><%= f.text_field :brand, placeholder: "Enter a brand, or homemade/unknown" %></p>
<p><%= f.text_area :description, placeholder: "Enter an item description" %></p>
<p><%= f.text_area :returnable, placeholder: "Enter a returns policy (if you'd be open to having the item back, for example)", class: "returns" %></p>
<p class="price">Price:</p>
<p><%= f.number_field :price, step: :any %></p>
<p class="file"><%= f.file_field :image %></p>
<p><%= f.submit %></p>
<% end %>
</div>

app/views/items/show.html.erb
<%= link_to("Send payment now", new_order_path(@item), class: 'button is-link payment') %>

<div class="item">
  <h1><%= @item.name %></h1>
  <p>Description: <%= @item.description %></p>
  <p>Price: <%= link_to (number_to_currency @item.price), new_order_path(@item) %></p>
  <p>Brand: <%= @item.brand %></p>
  <div class="iteminfo"><p>Returns policy: <%= @item.returnable %></p></div>
  
  <% if current_user == @item.bucket.user || current_user.has_role?(:admin) %>
  <p><%= link_to "Edit this item", edit_bucket_item_path(@item.bucket, @item), class: "button is-link" %></p>
  <p><%= link_to "Delete this item", bucket_item_destroy_path(@item.bucket, @item), :data => {:confirm => 'Are you sure?'}, class: "button is-link" %></p>
  <% end %>
</div>
<% if @item.tagwords.count >= 1 %>
  <div class="tagwords">
    <p>Tagwords:</p>
    <div>
      <% @item.tagwords.each do |tag| %>
        <%= tag.tag %><%= current_user == @item.bucket.user ? (link_to "(x)", tagword_remove_path(@item.bucket, @item, tag)) : '' %><%= ", " %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @item.bucket.user == current_user %>

<div class="tagword_new">
  <%= form_with scope: :tagword, method: 'post', controller: 'tagwords', action: 'create', local: true do |f| %>

    <%= f.text_field :tag, placeholder: "New Tagword" %>
    <%= f.submit %>

  <% end %>
</div>

<% end %>

<span class="item_image"><%= image_tag @item.image if @item.image.attached? %></span>

app/views/users/show.html.erb
<div class="profile_banner">

  <h1><%= @user.username %>'s Profile Page</h1>

  <% if current_user == @user %>

    <p>Welcome back, <%= @user.username %>!</p>

    <p><%= link_to "View your location page", location_path(@user.location), class: "location" %></p>

    <% if @sold.count >= 1 %>
      <ul>
      <p>All of your sold items:</p>
      <% @sold.each do |item| %>
      <li><%= link_to item.name, bucket_item_path(item.bucket, item) %></li>
      </ul>
    <% end %>
    <% end %>
  <% end %>
</div>

<div class="profile">

<p>Username: <%= @user.username %></p>
<p>Joined Streetlight on: <%= (@user.created_at).to_s.split(" ")[0] %></p>
<div class="bucket_card">
  <h2>All of <%= @user.username %>'s current buckets:</h2>
</div>

<div class="user_buckets">
  
  <% @user.buckets.each do |bucket| %>
  <div class="bucket_card">
    <div>
      <p class="title"><%= link_to bucket.name, bucket_path(bucket) %></p>
    </div>
    <div>
      <p>"<%= bucket.description %>"</p>
    </div>
    <div>
      <p>Contents: <%= bucket.items.count %> items</p>
    </div>
  
  </div>
  <% end %>

</div>
</div>