config/routes.rb
Rails.application.routes.draw do
  get 'orders/:item_id/complete', to: 'orders#complete'
  get 'orders/:item_id/cancel', to: 'orders#cancel'
  get 'orders/:item_id', to: 'orders#new', as: 'new_order'
  get 'locations/new', to: 'locations#new', as: 'new_location'
  post 'locations/new', to: 'locations#create'
  post 'buckets/:bucket_id/items/new', to: 'items#create'
  post 'buckets/:bucket_id/items/:item_id/edit', to: 'items#update'
  post 'buckets/:bucket_id/items/:item_id', to: 'tagwords#create'
  get 'buckets/:bucket_id/items/:item_id/:tagword/remove', to: 'tagwords#remove', as: 'tagword_remove'
  resources :locations, only: [:show, :edit, :create, :update]
  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'buckets/user', to: 'buckets#user', as: 'user_buckets'

  resources :buckets do 
    get 'destroy', to: 'buckets#destroy', as: 'destroy' 
    post 'items/new', to: 'items#create'
    get 'items/:id/destroy', to: 'items#destroy', as: 'item_destroy'
    resources :items do
      
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  devise_for :users
  get 'users/:id', to: 'users#show', as: 'user_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  validates :name, presence: true, length: {minimum: 4}
  validates :description, presence: true, length: {minimum: 10}

  belongs_to :user
  has_many :items, dependent: :destroy

  
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, -> (sender_id, receiver_id) do
    where("(conversations.sender_id = ? AND conversations.receiver_id = ?) OR (conversations.receiver_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
  end

  def recipient(current_user)
    self.sender_id == current_user.id ? self.receiver : self.sender
  end

  def unread_message_count(current_user)
    return self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}
  validates :brand, presence: true, length: {minimum: 2}
  validates :description, presence: true, length: {minimum: 20}
  validates :returnable, presence: true
  validates :price, presence: true
  has_one_attached :image
  has_many :item_tagwords, dependent: :destroy
  has_many :tagwords, through: :item_tagwords
  

  belongs_to :bucket
end

app/models/item_tagword.rb
class ItemTagword < ApplicationRecord
  belongs_to :item
  belongs_to :tagword
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  geocoded_by :full_street_address

  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_street_address
    address
  end

  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles



belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/tagword.rb
class Tagword < ApplicationRecord
  has_many :item_tagwords, dependent: :destroy
  has_many :items, through: :item_tagwords
  validates :tag, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :assign_default_role
  has_many :buckets, dependent: :destroy
  validates :username, presence: true
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  has_one :location, dependent: :destroy
  has_many :conversations

  def assign_default_role
    add_role(:user)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :params_item, only: [:show, :edit]
  before_action :authenticate_user!
  before_action :ensure_user, only: :edit
  def index
    @items = Item.all
  end

  def show
    @tagword = Tagword.new
  end

  def new
    @item = Item.new
    @bucket = Bucket.find(params[:bucket_id])
  end

  def create 
    @bucket = Bucket.find(params[:bucket_id])
    @item = @bucket.items.new(item_params)
    @item.image.attach(item_params[:image])
    if @item.save
      redirect_to bucket_path(@bucket)
    else
      flash[:alert] = "Could not save this item!"
      render :new
    end
  end

  def edit
    
  end

  def update 
    @item = Item.find_by(item_params[:item_id])
    if @item.update(item_params)
      redirect_to bucket_item_path(@item.bucket, @item)
    else
      flash[:alert] = "Could not update item!"
      render :edit
    end
  end

  def destroy 
    
    @item = Item.find_by(id: params[:id])
    @bucket = Bucket.find_by(id: params[:bucket_id])
    @item.destroy
    redirect_to bucket_path(@bucket)
    
    
  end 

  private 

  def params_item
    @item = Item.find(params[:id])
  end

  # Paramater sanitization
  def ensure_user
    if (Item.find(params[:id]).bucket.user != current_user) && (current_user.has_role?(:admin) == false)
      flash[:alert] = "You are not authorized to view this page!"
      redirect_to root_path
    end
  end

  def item_params
    params.require(:item).permit(:name, :brand, :description, :returnable, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tagwords_helper.rb
module TagwordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streetlight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <% if current_user %>
    <div class="navbar">
      <div class="navbox">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button is-link navlink" %>
        <%= link_to 'Browse', buckets_path, class: "button is-link navlink" %>
      </div>

      <div class="navbox special">
      <%= link_to 'Your items', user_buckets_path, class: "button is-link navlink" %>

       <a href="<%= current_user.has_role?(:admin) ? "" : "/" %>"><div class="navbar_logo"><span class="logosvg"><%= image_tag("logo.svg") %></span></div></a>

      <% if @unreadmessages == true %>
        <%= link_to 'Your inbox', conversations_path, class: "button is-link navlink redbox" %>
      <% elsif @unreadmessages == false %>
        <%= link_to 'Your inbox', conversations_path, class: "button is-link navlink" %>
      <% end %>
      </div>

      <div class="navbox">
      <%= link_to 'Your profile', user_profile_path(current_user), class: "button is-link navlink" %>
      <%= link_to 'Home', root_path, class: "button is-link navlink" %>
      </div>
    </div>
    <% else %>
    <div class="navbar">
      <%= link_to 'Sign up', new_user_registration_path, class: "button navlink" %>
      <div class="navbar_logo unverified"><span class="logosvg"><%= image_tag("logo.svg") %></span></div>
      <%= link_to 'Sign in', new_user_session_path, class: "button navlink" %>
    </div>
    <% end %>
    <div class="alerts"><%= render 'layouts/alerts' %></div>
    
    <div class="bodycontent">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1 class="welcome">Welcome to Streetlight, <span class="glow"><%= current_user.username %></span>.</h1>

<div class="homepage_links">
<%= link_to "Browse current item buckets", buckets_path, class: "button is-link" %>
<%= link_to "View your conversations", conversations_path, class: "button is-link" %>
<%= link_to "Create a new bucket", new_bucket_path, class: "button is-link" %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h5>The following errors occurred while saving</h5>
      </div>

      <ul class="panel-body">
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>